# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "rhel60_64"
  config.vm.box_url = "http://puppetlabs.s3.amazonaws.com/pub/rhel60_64.box"
#  config.vm.provision :puppet, :module_path => "modules" do |puppet|
#    puppet.manifests_path = "."
#    puppet.manifest_file  = "init.pp"
#  end
end
