# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "squeeze64"
  config.vm.box_url = "http://dl.dropbox.com/u/937870/VMs/squeeze64.box"
#  config.vm.provision :puppet, :module_path => "modules" do |puppet|
#    puppet.manifests_path = "."
#    puppet.manifest_file  = "init.pp"
#  end
end

