# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "squeeze32"
  config.vm.box_url = "http://mathie-vagrant-boxes.s3.amazonaws.com/debian_squeeze_32.box"
#  config.vm.provision :puppet, :module_path => "modules" do |puppet|
#    puppet.manifests_path = "."
#    puppet.manifest_file  = "init.pp"
#  end
end

